# Python Variables

In [1]:
x = 5
name = "Samantha"
print(x)
print(name)

5
Samantha

In [2]:
x = 5
y = 3.14
z = "Hi"

In [3]:
x = 10
x = "Now a string"

In [4]:
a = b = c = 100
print(a, b, c)

100 100 100

type casting varibles

In [5]:
s = "10"
n = int(s)

cnt = 5
f = float(cnt)

age = 25
s2 = str(age)

print(n)
print(f)
print(s2)

10
5.0
25

type of variables

In [6]:
n = 42
f = 3.14
s = "Hello, World!"
li = [1, 2, 3]
d = {'key': 'value'}
b = True

print(type(n))
print(type(f))
print(type(s))
print(type(li))
print(type(d))
print(type(b))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'dict'>
<class 'bool'>

In [7]:
x = 10
del x
print(x)

NameError: name 'x' is not defined

In [8]:
a, b = 5, 10
a, b = b, a
print(a, b)

10 5

In [9]:
word = "Python"
length = len(word)
print("Length of the word:", length)

Length of the word: 6

# Operators

In [10]:
# Variables
a = 15
b = 4

# Addition
print("Addition:", a + b)

# Subtraction
print("Subtraction:", a - b)

# Multiplication
print("Multiplication:", a * b)

# Division
print("Division:", a / b)

# Floor Division
print("Floor Division:", a // b)

# Modulus
print("Modulus:", a % b)

# Exponentiation
print("Exponentiation:", a ** b)

Addition: 19
Subtraction: 11
Multiplication: 60
Division: 3.75
Floor Division: 3
Modulus: 3
Exponentiation: 50625

In [11]:
a = 13
b = 33

print(a > b)
print(a < b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)

False
True
False
True
False
True

In [12]:
a = True
b = False
print(a and b)
print(a or b)
print(not a)

False
True
False

In [13]:
a = 10
b = 4

print(a & b)
print(a | b)
print(~a)
print(a ^ b)
print(a >> 2)
print(a << 2)

0
14
-11
14
2
40

In [14]:
a = 10
b = a
print(b)
b += a
print(b)
b -= a
print(b)
b *= a
print(b)
b <<= a
print(b)

10
20
10
100
102400

In [15]:
a = 10
b = 20
c = a

print(a is not b)
print(a is c)

True
True

In [16]:
x = 24
y = 20
list = [10, 20, 30, 40, 50]

if (x not in list):
    print("x is NOT present in given list")
else:
    print("x is present in given list")

if (y in list):
    print("y is present in given list")
else:
    print("y is NOT present in given list")

x is NOT present in given list
y is present in given list

In [17]:
a, b = 10, 20
min = a if a < b else b

print(min)

10

In [20]:
expr = 10 + 20 * 30
print(expr)
name = "Alex"
age = 0

if name == "Alex" or name == "John" and age >= 2:
    print("Hello! Welcome.")
else:
    print("Good Bye!!")

610
Hello! Welcome.

In [21]:
print(100 / 10 * 10)
print(5 - 2 + 3)
print(5 - (2 + 3))
print(2 ** 3 ** 2)

100.0
6
0
512

# Data Types

In [22]:
x = 50  # int
x = 60.5  # float
x = "Hello World"  # string
x = ["geeks", "for", "geeks"]  # list
x = ("geeks", "for", "geeks")  # tuple

In [23]:
a = 5
print(type(a))

b = 5.0
print(type(b))

c = 2 + 4j
print(type(c))

<class 'int'>
<class 'float'>
<class 'complex'>

In [24]:
s = 'Welcome to the Geeks World'
print(s)

# check data type
print(type(s))

# access string with index
print(s[1])
print(s[2])
print(s[-1]) # -1 refers to the last character, -2 is second last, and so on

Welcome to the Geeks World
<class 'str'>
e
l
d

In [25]:
# Empty list
a = []

# list with int values
a = [1, 2, 3]
print(a)

# list with mixed values int and String
b = ["Geeks", "For", "Geeks", 4, 5]
print(b)

[1, 2, 3]
['Geeks', 'For', 'Geeks', 4, 5]

In [26]:
a = ["Geeks", "For", "Geeks"]
print("Accessing element from the list")
print(a[0])
print(a[2])

print("Accessing element using negative indexing")
print(a[-1])
print(a[-3])

Accessing element from the list
Geeks
Geeks
Accessing element using negative indexing
Geeks
Geeks

In [27]:
# initiate empty tuple
tup1 = ()

tup2 = ('Geeks', 'For')
print("\nTuple with the use of String: ", tup2)

Tuple with the use of String:  ('Geeks', 'For')

In [28]:
tup1 = (1, 2, 3, 4, 5)

# access tuple items
print(tup1[0])
print(tup1[-1])
print(tup1[-3])

1
5
3

In [29]:
print(type(True))
print(type(False))
print(type(true))

<class 'bool'>
<class 'bool'>

NameError: name 'true' is not defined

In [30]:
if 1:
    print("1 is truthy")

if not 0:
    print("0 is falsy")

1 is truthy
0 is falsy

In [31]:
# initializing empty set
s1 = set()

s1 = set("GeeksForGeeks")
print("Set with the use of String: ", s1)

s2 = set(["Geeks", "For", "Geeks"])
print("Set with the use of List: ", s2)

Set with the use of String:  {'F', 'e', 'o', 'k', 'r', 'G', 's'}
Set with the use of List:  {'Geeks', 'For'}

In [32]:
set1 = set(["Geeks", "For", "Geeks"]) #Duplicates are removed automatically
print(set1)

# loop through set
for i in set1:
   print(i, end=" ") #prints elements one by one

# check if item exist in set
print("Geeks" in set1)

{'Geeks', 'For'}
Geeks For True

In [33]:
# initialize empty dictionary
d = {}

d = {1: 'Geeks', 2: 'For', 3: 'Geeks'}
print(d)

# creating dictionary using dict() constructor
d1 = dict({1: 'Geeks', 2: 'For', 3: 'Geeks'})
print(d1)

{1: 'Geeks', 2: 'For', 3: 'Geeks'}
{1: 'Geeks', 2: 'For', 3: 'Geeks'}

In [34]:
d = {1: 'Geeks', 'name': 'For', 3: 'Geeks'}

# Accessing an element using key
print(d['name'])

# Accessing a element using get
print(d.get(3))

For
Geeks

#Conditional Statements

In [36]:
age = 20
if age >= 18:
    print("Eligible to vote.")

age = 19
if age > 18: print("Eligible to Vote.")

Eligible to vote.

In [38]:
age = 10
if age <= 12:
    print("Travel for free.")
else:
    print("Pay for ticket.")

marks = 45
res = "Pass" if marks >= 40 else "Fail"
print(f"Result: {res}")

Travel for free.
Result: Pass

In [39]:
age = 25

if age <= 12:
    print("Child.")
elif age <= 19:
    print("Teenager.")
elif age <= 35:
    print("Young adult.")
else:
    print("Adult.")

Young adult.

In [40]:
age = 70
is_member = True

if age >= 60:
    if is_member:
        print("30% senior discount!")
    else:
        print("20% senior discount.")
else:
    print("Not eligible for a senior discount.")

30% senior discount!

In [41]:
# Assign a value based on a condition
age = 20
s = "Adult" if age >= 18 else "Minor"
print(s)

Adult

In [42]:
number = 2

match number:
    case 1:
        print("One")
    case 2 | 3:
        print("Two or Three")
    case _:
        print("Other number")

Two or Three

#Loops

In [43]:
n = 4
for i in range(0, n):
    print(i)

0
1
2
3

In [44]:
li = ["geeks", "for", "geeks"]
for x in li:
    print(x)

tup = ("geeks", "for", "geeks")
for x in tup:
    print(x)

s = "abc"
for x in s:
    print(x)

d = dict({'x':123, 'y':354})
for x in d:
    print("%s  %d" % (x, d[x]))

set1 = {10, 30, 20}
for x in set1:
    print(x),

geeks
for
geeks
geeks
for
geeks
a
b
c
x  123
y  354
10
20
30

In [45]:
li = ["geeks", "for", "geeks"]
for index in range(len(li)):
    print(li[index])

geeks
for
geeks

In [46]:
cnt = 0
while (cnt < 3):
    cnt = cnt + 1
    print("Hello Geek")

Hello Geek
Hello Geek
Hello Geek

In [48]:
while (True):
    print("Hello Geek")

Streaming output truncated to the last 5000 lines.
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek
Hello Geek

KeyboardInterrupt:

In [49]:
from __future__ import print_function
for i in range(1, 5):
    for j in range(i):
        print(i, end=' ')
    print()

1
2 2
3 3 3
4 4 4 4

In [50]:
for letter in 'geeksforgeeks':
    if letter == 'e' or letter == 's':
        continue
    print('Current Letter :', letter)

Current Letter : g
Current Letter : k
Current Letter : f
Current Letter : o
Current Letter : r
Current Letter : g
Current Letter : k

In [51]:
for letter in 'geeksforgeeks':
    if letter == 'e' or letter == 's':
        break

print('Current Letter :', letter)

Current Letter : e

In [52]:
for letter in 'geeksforgeeks':
    pass
print('Last Letter :', letter)

Last Letter : s

# Functions

In [54]:
def fun():
    print("Welcome to GFG")

fun() # Driver code to call a function

Welcome to GFG

In [55]:
def evenOdd(x):
    if (x % 2 == 0):
        return "Even"
    else:
        return "Odd"

print(evenOdd(16))
print(evenOdd(7))

Even
Odd

In [56]:
def myFun(x, y=50):
    print("x: ", x)
    print("y: ", y)

myFun(10)

x:  10
y:  50

In [57]:
def student(fname, lname):
    print(fname, lname)

student(fname='Geeks', lname='Practice')
student(lname='Practice', fname='Geeks')

Geeks Practice
Geeks Practice

In [58]:
def nameAge(name, age):
    print("Hi, I am", name)
    print("My age is ", age)

print("Case-1:")
nameAge("Suraj", 27)

print("\nCase-2:")
nameAge(27, "Suraj")

Case-1:
Hi, I am Suraj
My age is  27

Case-2:
Hi, I am 27
My age is  Suraj

In [59]:
def myFun(*args, **kwargs):
    print("Non-Keyword Arguments (*args):")
    for arg in args:
        print(arg)

    print("\nKeyword Arguments (**kwargs):")
    for key, value in kwargs.items():
        print(f"{key} == {value}")

# Function call with both types of arguments
myFun('Hey', 'Welcome', first='Geeks', mid='for', last='Geeks')

Non-Keyword Arguments (*args):
Hey
Welcome

Keyword Arguments (**kwargs):
first == Geeks
mid == for
last == Geeks

In [60]:
def f1():
    s = 'I love GeeksforGeeks'
    def f2():
        print(s)

    f2()
f1()

I love GeeksforGeeks

In [61]:
def cube(x): return x*x*x   # without lambda
cube_l = lambda x : x*x*x  # with lambda

print(cube(7))
print(cube_l(7))

343
343

In [62]:
def square_value(num):
    """This function returns the square
    value of the entered number"""
    return num**2

print(square_value(2))
print(square_value(-4))

4
16

In [63]:
# Function modifies the first element of list
def myFun(x):
    x[0] = 20

lst = [10, 11, 12, 13]
myFun(lst)
print(lst)   # list is modified

# Function tries to modify an integer
def myFun2(x):
    x = 20

a = 10
myFun2(a)
print(a)     # integer is not modified

[20, 11, 12, 13]
10

In [64]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(4))

24

local variable

In [65]:
def greet():
    msg = "Hello from inside the function!"
    print(msg)

greet()

Hello from inside the function!

In [66]:
def greet():
    msg = "Hello!"
    print("Inside function:", msg)

greet()
print("Outside function:", msg)

Inside function: Hello!

NameError: name 'msg' is not defined

global variable

In [67]:
msg = "Python is awesome!"

def display():
    print("Inside function:", msg)

display()
print("Outside function:", msg)

Inside function: Python is awesome!
Outside function: Python is awesome!

In [68]:
def fun():
    s = "Me too."
    print(s)

s = "I love Geeksforgeeks"
fun()
print(s)

Me too.
I love Geeksforgeeks

In [69]:
def fun():
    s += ' GFG'   # Error: Python thinks s is local
    print(s)

s = "I love GeeksforGeeks"
fun()

UnboundLocalError: cannot access local variable 's' where it is not associated with a value

In [70]:
s = "Python is great!"

def fun():
    global s
    s += " GFG"   # Modify global variable
    print(s)
    s = "Look for GeeksforGeeks Python Section"  # Reassign global
    print(s)

fun()
print(s)

Python is great! GFG
Look for GeeksforGeeks Python Section
Look for GeeksforGeeks Python Section

In [71]:
a = 1  # Global variable

def f():
    print("f():", a)  # Uses global a

def g():
    a = 2  # Local shadows global
    print("g():", a)

def h():
    global a
    a = 3  # Modifies global a
    print("h():", a)

print("global:", a)
f()
print("global:", a)
g()
print("global:", a)
h()
print("global:", a)

global: 1
f(): 1
global: 1
g(): 2
global: 1
h(): 3
global: 3

# Recursion

In [72]:
def factorial(n):
    if n == 0:  # Base case
        return 1
    else:       # Recursive case
        return n * factorial(n - 1)

print(factorial(5))

120

In [73]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(10))

55

In [74]:
def tail_fact(n, acc=1):
    # Base case
    if n == 0:
        return acc
    # Tail recursive call with an accumulator
    else:
        return tail_fact(n-1, acc * n)

def nontail_fact(n):
    # Base case
    if n == 1:
        return 1
    # Non-tail recursive call because the multiplication happens after the call
    else:
        return n * nontail_fact(n-1)

# Example usage
print(tail_fact(5))
print(nontail_fact(5))

120
120

# self

In [75]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand  # Set instance attribute
        self.model = model  # Set instance attribute

    def display(self):
        return self.brand, self.model

# Create an instance of Car
car1 = Car("Toyota", "Corolla")

# Call the display method
print(car1.display())

('Toyota', 'Corolla')

In [76]:
class gfg:
    def __init__(self, topic):
        self._topic = topic  # Store parameter value in instance variable

    def topic(self):
        print("Topic:", self._topic)  # Access the renamed variable

# Creating an instance of gfg
ins = gfg("Python")

# Calling the topic method
ins.topic()

Topic: Python

In [77]:
class Circle:
    def __init__(self, r):
        self.r = r

    def area(self):
        a = 3.14 * self.r ** 2
        return a

# Creating an instance of Circle
ins = Circle(5)

# Calling the area method
print("Area of the circle:", ins.area())

Area of the circle: 78.5

# lambda function

In [78]:
a = 'GeeksforGeeks'
upper = lambda x: x.upper()
print(upper(a))

GEEKSFORGEEKS

In [79]:
check = lambda x: "Positive" if x > 0 else "Negative" if x < 0 else "Zero"
print(check(5))
print(check(-3))
print(check(0))

Positive
Negative
Zero

In [80]:
check = lambda x: "Even" if x % 2 == 0 else "Odd"
print(check(4))
print(check(7))

Even
Odd

In [81]:
func = [lambda arg=x: arg * 10 for x in range(1, 5)]
for i in func:
    print(i())

10
20
30
40

In [82]:
calc = lambda x, y: (x + y, x * y)
res = calc(3, 4)
print(res)

(7, 12)

In [85]:
c = [1, 2, 3, 4, 5, 6]
even = filter(lambda x: x % 2 == 0, c)
print(even)

<filter object at 0x79e17bdfea40>

In [89]:
a = [1, 2, 3, 4]
double = map(lambda x: x * 2, a)
result_list = __builtins__.list(double)
print(result_list)

[2, 4, 6, 8]

In [90]:
from functools import reduce
a = [1, 2, 3, 4]
mul = reduce(lambda x, y: x * y, a)
print(mul)

24

In [88]:
# Using lambda
square = lambda x: x ** 2
print(square(3))

# Using def
def sqdef(x):
    return x ** 2
print(sqdef(3))

9
9

# decorator

In [91]:
def decorator(func):
    def wrapper():
        print("Before calling the function.")
        func()
        print("After calling the function.")
    return wrapper

@decorator # Applying the decorator to a function
def greet():
    print("Hello, World!")
greet()

Before calling the function.
Hello, World!
After calling the function.

In [92]:
def decorator_name(func):
    def wrapper(*args, **kwargs):
        print("Before execution")
        result = func(*args, **kwargs)
        print("After execution")
        return result
    return wrapper

@decorator_name
def add(a, b):
    return a + b

print(add(5, 3))

Before execution
After execution
8

In [93]:
# Assigning a function to a variable
def greet(n):
    return f"Hello, {n}!"
say_hi = greet  # Assign the greet function to say_hi
print(say_hi("Alice"))

# Passing a function as an argument
def apply(f, v):
    return f(v)
res = apply(say_hi, "Bob")
print(res)

# Returning a function from another function
def make_mult(f):
    def mult(x):
        return x * f
    return mult
dbl = make_mult(2)
print(dbl(5))

Hello, Alice!
Hello, Bob!
10

In [94]:
# A higher-order function that takes another function as an argument
def fun(f, x):
    return f(x)

# A simple function to pass
def square(x):
    return x * x
res = fun(square, 5) # Using apply_function to apply the square function
print(res)

25

In [95]:
def simple_decorator(func):
    def wrapper():
        print(">>> Starting function")
        func()
        print(">>> Function finished")
    return wrapper

@simple_decorator
def greet():
    print("Hello, World!")
greet()

>>> Starting function
Hello, World!
>>> Function finished

In [96]:
def method_decorator(func):
    def wrapper(self, *args, **kwargs):
        print("Before method execution")
        res = func(self, *args, **kwargs)
        print("After method execution")
        return res
    return wrapper

class MyClass:
    @method_decorator
    def say_hello(self):
        print("Hello!")
obj = MyClass()
obj.say_hello()

Before method execution
Hello!
After method execution

In [97]:
def fun(cls):
    cls.class_name = cls.__name__
    return cls

@fun
class Person:
    pass
print(Person.class_name)

Person

In [98]:
class MathOperations:
    @staticmethod
    def add(x, y):
        return x + y

# Using the static method
res = MathOperations.add(5, 3)
print(res)

8

In [99]:
class Employee:
    raise_amount = 1.05
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    @classmethod
    def set_raise_amount(cls, amount):
        cls.raise_amount = amount

# Using the class method
Employee.set_raise_amount(1.10)
print(Employee.raise_amount)

1.1

In [100]:
class Circle:
    def __init__(self, radius):
        self._radius = radius

    @property
    def radius(self):
        return self._radius

    @radius.setter
    def radius(self, value):
        if value >= 0:
            self._radius = value
        else:
            raise ValueError("Radius cannot be negative")

    @property
    def area(self):
        return 3.14159 * (self._radius ** 2)

# Using the property
c = Circle(5)
print(c.radius)
print(c.area)
c.radius = 10
print(c.area)

5
78.53975
314.159

In [101]:
def decor1(func):
    def inner():
        x = func()
        return x * x
    return inner

def decor(func):
    def inner():
        x = func()
        return 2 * x
    return inner

@decor1
@decor
def num():
    return 10

@decor
@decor1
def num2():
    return 10

print(num())
print(num2())

400
200

#String

In [102]:
s1 = 'GfG'  # single quote
s2 = "GfG"  # double quote
print(s1)
print(s2)

GfG
GfG

In [103]:
s = """I am Learning
Python String on GeeksforGeeks"""
print(s)

s = '''I'm a
Geek'''
print(s)

I am Learning
Python String on GeeksforGeeks
I'm a
Geek

In [104]:
s = "GeeksforGeeks"
print(s[0])   # first character
print(s[4])   # 5th character

G
s

In [105]:
s = "GeeksforGeeks"
print(s[-10])   # 3rd character
print(s[-5])    # 5th character from end

k
G

In [106]:
s = "GeeksforGeeks"
print(s[1:4])    # characters from index 1 to 3
print(s[:3])     # from start to index 2
print(s[3:])     # from index 3 to end
print(s[::-1])   # reverse string

eek
Gee
ksforGeeks
skeeGrofskeeG

In [107]:
s = "Python"
for char in s:
    print(char)

P
y
t
h
o
n

In [108]:
s = "geeksforGeeks"
s = "G" + s[1:]   # create new string
print(s)

GeeksforGeeks

In [109]:
s = "GfG"
del s

In [110]:
s = "hello geeks"
s1 = "H" + s[1:]                   # update first character
s2 = s.replace("geeks", "GeeksforGeeks")  # replace word
print(s1)
print(s2)

Hello geeks
hello GeeksforGeeks

In [111]:
s = "GeeksforGeeks"
print(len(s))

13

In [112]:
s = "   Gfg   "
print(s.strip())

s = "Python is fun"
print(s.replace("fun", "awesome"))

Gfg
Python is awesome

In [113]:
s1 = "Hello"
s2 = "World"
print(s1 + " " + s2)

Hello World

In [114]:
s = "Hello "
print(s * 3)

Hello Hello Hello

In [115]:
name = "Alice"
age = 22
print(f"Name: {name}, Age: {age}")

Name: Alice, Age: 22

In [116]:
s = "My name is {} and I am {} years old.".format("Alice", 22)
print(s)

My name is Alice and I am 22 years old.

In [117]:
s = "GeeksforGeeks"
print("Geeks" in s)
print("GfG" in s)

True
False

In [118]:
a = [1, 2, 3, 4, 5] # List of integers
b = ['apple', 'banana', 'cherry'] # List of strings
c = [1, 'hello', 3.14, True] # Mixed data types

print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
['apple', 'banana', 'cherry']
[1, 'hello', 3.14, True]

In [119]:
a = list((1, 2, 3, 'apple', 4.5))
print(a)

b = list("GFG")
print(b)

TypeError: 'list' object is not callable

In [120]:
a = [2] * 5
b = [0] * 7

print(a)
print(b)

[2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0]

In [121]:
a = [10, 20, 30, 40, 50]
print(a[0])
print(a[-1])
print(a[1:4])   # elements from index 1 to 3

10
50
[20, 30, 40]

In [122]:
a = []

a.append(10)
print("After append(10):", a)

a.insert(0, 5)
print("After insert(0, 5):", a)

a.extend([15, 20, 25])
print("After extend([15, 20, 25]):", a)

a.clear()
print("After clear():", a)

After append(10): [10]
After insert(0, 5): [5, 10]
After extend([15, 20, 25]): [5, 10, 15, 20, 25]
After clear(): []

In [123]:
a = [10, 20, 30, 40, 50]
a[1] = 25
print(a)

[10, 25, 30, 40, 50]

In [124]:
a = [10, 20, 30, 40, 50]

a.remove(30)
print("After remove(30):", a)

popped_val = a.pop(1)
print("Popped element:", popped_val)
print("After pop(1):", a)

del a[0]
print("After del a[0]:", a)

After remove(30): [10, 20, 40, 50]
Popped element: 20
After pop(1): [10, 40, 50]
After del a[0]: [40, 50]

In [125]:
a = ['apple', 'banana', 'cherry']
for item in a:
    print(item)

apple
banana
cherry

In [126]:
matrix = [ [1, 2, 3],
           [4, 5, 6],
           [7, 8, 9] ]
print(matrix[1][2])

6

In [127]:
squares = [x**2 for x in range(1, 6)]
print(squares)

[1, 4, 9, 16, 25]

In [128]:
a = [10, 20, "GfG", 40, True]
print(a)
print(a[0])
print(a[1])
print(a[2])

[10, 20, 'GfG', 40, True]
10
20
GfG

In [129]:
data = { "name": "Jake", "age": 22 }
print(data)

{'name': 'Jake', 'age': 22}

In [130]:
d = {1: 'Geeks', 2: 'For', 3: 'Geeks'}

# Adding a new key-value pair
d["age"] = 22

# Updating an existing value
d[1] = "Python dict"
print(d)

{1: 'Python dict', 2: 'For', 3: 'Geeks', 'age': 22}

In [131]:
d = {1: 'Geeks', 2: 'For', 3: 'Geeks', 'age':22}

# Using del
del d["age"]
print(d)

# Using pop()
val = d.pop(1)
print(val)

# Using popitem()
key, val = d.popitem()
print(f"Key: {key}, Value: {val}")

# Using clear()
d.clear()
print(d)

{1: 'Geeks', 2: 'For', 3: 'Geeks'}
Geeks
Key: 3, Value: Geeks
{}

In [132]:
d = {1: 'Geeks', 2: 'For', 'age':22}

# Iterate over keys
for key in d:
    print(key)

# Iterate over values
for value in d.values():
    print(value)

# Iterate over key-value pairs
for key, value in d.items():
    print(f"{key}: {value}")

1
2
age
Geeks
For
22
1: Geeks
2: For
age: 22

In [133]:
d = {1: 'Geeks', 2: 'For', 3: {'A': 'Welcome', 'B': 'To', 'C': 'Geeks'}}
print(d)

{1: 'Geeks', 2: 'For', 3: {'A': 'Welcome', 'B': 'To', 'C': 'Geeks'}}

In [134]:
tup = ()
print(tup)

# Using String
tup = ('Geeks', 'For')
print(tup)

# Using List
li = [1, 2, 4, 5, 6]
print(tuple(li))

# Using Built-in Function
tup = tuple('Geeks')
print(tup)

()
('Geeks', 'For')
(1, 2, 4, 5, 6)
('G', 'e', 'e', 'k', 's')

In [135]:
tup = (5, 'Welcome', 7, 'Geeks')
print(tup)

# Creating a Tuple with nested tuples
tup1 = (0, 1, 2, 3)
tup2 = ('python', 'geek')
tup3 = (tup1, tup2)
print(tup3)

# Creating a Tuple with repetition
tup1 = ('Geeks',) * 3
print(tup1)

(5, 'Welcome', 7, 'Geeks')
((0, 1, 2, 3), ('python', 'geek'))
('Geeks', 'Geeks', 'Geeks')

In [136]:
# Accessing Tuple with Indexing
tup = tuple("Geeks")
print(tup[0])

# Accessing a range of elements using slicing
print(tup[1:4])
print(tup[:3])

# Tuple unpacking
tup = ("Geeks", "For", "Geeks")

# This line unpack values of Tuple1
a, b, c = tup
print(a)
print(b)
print(c)

G
('e', 'e', 'k')
('G', 'e', 'e')
Geeks
For
Geeks

In [137]:
tup1 = (0, 1, 2, 3)
tup2 = ('Geeks', 'For', 'Geeks')

tup3 = tup1 + tup2
print(tup3)

(0, 1, 2, 3, 'Geeks', 'For', 'Geeks')

In [138]:
tup = tuple('GEEKSFORGEEKS')

# Removing First element
print(tup[1:])

# Reversing the Tuple
print(tup[::-1])

# Printing elements of a Range
print(tup[4:9])

('E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S')
('S', 'K', 'E', 'E', 'G', 'R', 'O', 'F', 'S', 'K', 'E', 'E', 'G')
('S', 'F', 'O', 'R', 'G')

In [139]:
tup = (0, 1, 2, 3, 4)
del tup

print(tup)

NameError: name 'tup' is not defined

In [140]:
tup = (1, 2, 3, 4, 5)

a, *b, c = tup

print(a)
print(b)
print(c)

1
[2, 3, 4]
5

In [141]:
a = [1, "Hello", [3.14, "world"]]
a.append(2)  # Add an integer to the end
print(a)

[1, 'Hello', [3.14, 'world'], 2]

In [142]:
import numpy as np
a = np.array([1, 2, 3, 4])

# Element-wise operations
print(a * 2)

# Multi-dimensional array
res = np.array([[1, 2], [3, 4]])
print(res * 2)

[2 4 6 8]
[[2 4]
 [6 8]]

In [143]:
import array as arr
a = arr.array('i', [1, 2, 3])

# accessing First Araay
print(a[0])

# adding element to array
a.append(5)
print(a)

1
array('i', [1, 2, 3, 5])

In [144]:
import array as arr
a = arr.array('i', [1, 2, 3])

for i in range(0, 3):
    print(a[i], end=" ")

1 2 3

In [145]:
import array as arr
a = arr.array('i', [1, 2, 3])
print(*a)

a.insert(1, 4)  # Insert 4 at index 1
print(*a)

1 2 3
1 4 2 3

In [146]:
import array as arr
a = arr.array('i', [1, 2, 3, 4, 5, 6])

print(a[0])
print(a[3])

b = arr.array('d', [2.5, 3.2, 3.3])
print(b[1])
print(b[2])

1
4
3.2
3.3

In [147]:
import array
a = array.array('i', [1, 2, 3, 1, 5])

# remove first occurance of 1
a.remove(1)
print(a)

# remove item at index 2
a.pop(2)
print(a)

array('i', [2, 3, 1, 5])
array('i', [2, 3, 5])

In [148]:
import array as arr
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = arr.array('i', a)

res = a[3:8]
print(res)

res = a[5:]
print(res)

res = a[:]
print(res)

[4, 5, 6, 7, 8]
[6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [149]:
import array
a = array.array('i', [1, 2, 3, 1, 2, 5])

# index of 1st occurrence of 2
print(a.index(2))

# index of 1st occurrence of 1
print(a.index(1))

1
0

In [150]:
import array
a = array.array('i', [1, 2, 3, 1, 2, 5])

# update item at index 2
a[2] = 6
print(a)

# update item at index 4
a[4] = 8
print(a)

array('i', [1, 2, 6, 1, 2, 5])
array('i', [1, 2, 6, 1, 8, 5])

In [151]:
import array
a = array.array('i', [1, 2, 3, 4, 2, 5, 2])

count = a.count(2)
print(count)

3

In [152]:
import array
a = array.array('i', [1, 2, 3, 4, 5])

a.reverse()
print(*a)

5 4 3 2 1

In [153]:
import array as arr
a = arr.array('i', [1, 2, 3,4,5])

a.extend([6,7,8,9,10])
print(a)

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [154]:
s = {1, 2, 3, 4}
print(s)

{1, 2, 3, 4}

In [155]:
s = set()
print(s)

s = set("GeeksForGeeks")
print(s)

# Creating a Set with the use of a List
s = set(["GFG", "For", "Geeks"])
print(s)

# Creating a Set with the use of a tuple
t = ("GFG", "for", "Geeks")
print(set(t))

# Creating a Set with the use of a dictionary
d = {"GFG": 1, "for": 2, "Geeks": 3}
print(set(d))

set()
{'F', 'e', 'o', 'k', 'r', 'G', 's'}
{'Geeks', 'For', 'GFG'}
{'Geeks', 'for', 'GFG'}
{'Geeks', 'for', 'GFG'}

In [156]:
s = {3, 1, 4, 1, 5, 9, 2}

print(s)  # Output may vary: {1, 2, 3, 4, 5, 9}

# Unindexed: Accessing elements by index is not possible
# This will raise a TypeError
try:
    print(s[0])
except TypeError as e:
    print(e)

{1, 2, 3, 4, 5, 9}
'set' object is not subscriptable

In [157]:
s = {1, 2, 3}

# Add one item
s.add(4)

# Add multiple items
s.update([5, 6])

print(s)

{1, 2, 3, 4, 5, 6}

In [158]:
s = {"Geeks", "For", "Geeks"}

# 1. Accessing elements using a for loop
for i in s:
    print(i, end=" ")

# 2. Checking if an element exists using the 'in' keyword
print("\n", "Geeks" in s)

Geeks For
 True

In [159]:
# Using Remove Method
s = {1, 2, 3, 4, 5}
s.remove(3)
print(s)

# Attempting to remove an element that does not exist
try:
    s.remove(10)
except KeyError as e:
    print("Error:", e)

# Using discard() Method
s.discard(4)
print(s)

# Attempting to discard an element that does not exist
s.discard(10)  # No error raised
print(s)

{1, 2, 4, 5}
Error: 10
{1, 2, 5}
{1, 2, 5}

In [160]:
s = {1, 2, 3, 4, 5}
val = s.pop()
print(val)
print(s)

# Using pop on an empty set
s.clear()  # Clear the set to make it empty
try:
    s.pop()
except KeyError as e:
    print("Error:", e)

1
{2, 3, 4, 5}
Error: 'pop from an empty set'

In [161]:
# Creating a frozenset from a list
fs = frozenset([1, 2, 3, 4, 5])
print(fs)

# Creating a frozenset from a set
s = {3, 1, 4, 1, 5}
fs = frozenset(s)
print(fs)

frozenset({1, 2, 3, 4, 5})
frozenset({1, 3, 4, 5})

In [162]:
# Typecasting list into set
li = [1, 2, 3, 3, 4, 5, 5, 6, 2]
s = set(li)
print(s)

# Typecasting string into set
s = "GeeksforGeeks"
s = set(s)
print(s)

# Typecasting dictionary into set
d = {1: "One", 2: "Two", 3: "Three"}
s = set(d)
print(s)

{1, 2, 3, 4, 5, 6}
{'f', 'e', 'o', 'k', 'r', 'G', 's'}
{1, 2, 3}

In [163]:
from collections import Counter
# Create a list of items
num = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]

# Use Counter to count occurrences
cnt = Counter(num)
print(cnt)

Counter({4: 4, 3: 3, 2: 2, 1: 1})

In [164]:
from collections import Counter
ctr1 = Counter([1, 2, 2, 3, 3, 3]) # From a list
ctr2 = Counter({1: 2, 2: 3, 3: 1}) # From a dictionary
ctr3 = Counter('hello') # From a string

print(ctr1)
print(ctr2)
print(ctr3)

Counter({3: 3, 2: 2, 1: 1})
Counter({2: 3, 1: 2, 3: 1})
Counter({'l': 2, 'h': 1, 'e': 1, 'o': 1})

In [165]:
from collections import Counter
ctr = Counter([1, 2, 2, 3, 3, 3])

# Accessing count of an element
print(ctr[1])
print(ctr[2])
print(ctr[3])
print(ctr[4])  # (element not present)

1
2
3
0

In [166]:
from collections import Counter
ctr = Counter([1, 2, 2])
ctr.update([2, 3, 3, 3])
print(ctr)

Counter({2: 3, 3: 3, 1: 1})

# OOP

In [169]:
class Dog:
    # Class variable
    species = "Canine"

    def __init__(self, name, age):
        # Instance variables
        self.name = name
        self.age = age

# Create objects
dog1 = Dog("Buddy", 3)
dog2 = Dog("Charlie", 5)

# Access class and instance variables
print(dog1.species)  # (Class variable)
print(dog1.name)     # (Instance variable)
print(dog2.name)     # (Instance variable)

# Modify instance variables
dog1.name = "Max"
print(dog1.name)     # (Updated instance variable)

# Modify class variable
Dog.species = "Feline"
print(dog1.species)  # (Updated class variable)
print(dog2.species)

Canine
Buddy
Charlie
Max
Feline
Feline

In [170]:
class Calculator:
    def multiply(self, a=1, b=1, *args):
        result = a * b
        for num in args:
            result *= num
        return result

# Create object
calc = Calculator()

# Using default arguments
print(calc.multiply())
print(calc.multiply(4))

# Using multiple arguments
print(calc.multiply(2, 3))
print(calc.multiply(2, 3, 4))

1
4
6
24

In [171]:
class Animal:
    def sound(self):
        return "Some generic sound"

class Dog(Animal):
    def sound(self):
        return "Bark"

class Cat(Animal):
    def sound(self):
        return "Meow"

# Polymorphic behavior
animals = [Dog(), Cat(), Animal()]
for animal in animals:
    print(animal.sound())

Bark
Meow
Some generic sound

In [172]:
print(len("Hello"))  # String length
print(len([1, 2, 3]))  # List length

print(max(1, 3, 2))  # Maximum of integers
print(max("a", "z", "m"))  # Maximum in strings

5
3
3
z

In [173]:
class Pen:
    def use(self):
        return "Writing"

class Eraser:
    def use(self):
        return "Erasing"

def perform_task(tool):
    print(tool.use())

perform_task(Pen())
perform_task(Eraser())

Writing
Erasing

In [174]:
print(5 + 10)  # Integer addition
print("Hello " + "World!")  # String concatenation
print([1, 2] + [3, 4])  # List concatenation

15
Hello World!
[1, 2, 3, 4]

In [175]:
class Animal:
    def __init__(self, name):
        self.name = name

    def info(self):
        print("Animal name:", self.name)

class Dog(Animal):
    def sound(self):
        print(self.name, "barks")

d = Dog("Buddy")
d.info()      # Inherited method
d.sound()

Animal name: Buddy
Buddy barks

In [176]:
# Parent Class: Animal
class Animal:
    def __init__(self, name):
        self.name = name

    def info(self):
        print("Animal name:", self.name)

# Child Class: Dog
class Dog(Animal):
    def __init__(self, name, breed):
        super().__init__(name)   # Call parent constructor
        self.breed = breed

    def details(self):
        print(self.name, "is a", self.breed)

d = Dog("Buddy", "Golden Retriever")
d.info()      # Parent method
d.details()   # Child method

Animal name: Buddy
Buddy is a Golden Retriever

In [177]:
class Person:
    def __init__(self, name):
        self.name = name

class Employee(Person):  # Employee inherits from Person
    def show_role(self):
        print(self.name, "is an employee")

emp = Employee("Sarah")
print("Name:", emp.name)
emp.show_role()

Name: Sarah
Sarah is an employee

In [178]:
class Person:
    def __init__(self, name):
        self.name = name

class Job:
    def __init__(self, salary):
        self.salary = salary

class Employee(Person, Job):  # Inherits from both Person and Job
    def __init__(self, name, salary):
        Person.__init__(self, name)
        Job.__init__(self, salary)

    def details(self):
        print(self.name, "earns", self.salary)

emp = Employee("Jennifer", 50000)
emp.details()

Jennifer earns 50000

In [179]:
class Person:
    def __init__(self, name):
        self.name = name

class Employee(Person):
    def show_role(self):
        print(self.name, "is an employee")

class Manager(Employee):  # Manager inherits from Employee
    def department(self, dept):
        print(self.name, "manages", dept, "department")

mgr = Manager("Joy")
mgr.show_role()
mgr.department("HR")

Joy is an employee
Joy manages HR department

In [180]:
class Person:
    def __init__(self, name):
        self.name = name

class Employee(Person):
    def role(self):
        print(self.name, "works as an employee")

class Intern(Person):
    def role(self):
        print(self.name, "is an intern")

emp = Employee("David")
emp.role()

intern = Intern("Eva")
intern.role()

David works as an employee
Eva is an intern

In [181]:
class Person:
    def __init__(self, name):
        self.name = name

class Employee(Person):
    def role(self):
        print(self.name, "is an employee")

class Project:
    def __init__(self, project_name):
        self.project_name = project_name

class TeamLead(Employee, Project):  # Hybrid Inheritance
    def __init__(self, name, project_name):
        Employee.__init__(self, name)
        Project.__init__(self, project_name)

    def details(self):
        print(self.name, "leads project:", self.project_name)

lead = TeamLead("Sophia", "AI Development")
lead.role()
lead.details()

Sophia is an employee
Sophia leads project: AI Development

In [182]:
from abc import ABC, abstractmethod

class Greet(ABC):
    @abstractmethod
    def say_hello(self):
        pass  # Abstract method

class English(Greet):
    def say_hello(self):
        return "Hello!"

g = English()
print(g.say_hello())

Hello!

In [183]:
from abc import ABC, abstractmethod
class Animal(ABC):
    @abstractmethod
    def make_sound(self):
        pass  # Abstract method, no implementation here

In [184]:
from abc import ABC, abstractmethod

class Animal(ABC):
    @property
    @abstractmethod
    def species(self):
        pass  # Abstract property, must be implemented by subclasses

class Dog(Animal):
    @property
    def species(self):
        return "Canine"

# Instantiate the concrete subclass
dog = Dog()
print(dog.species)

Canine

In [185]:
from abc import ABC, abstractmethod

class Animal(ABC):
    @abstractmethod
    def make_sound(self):
        pass

animal = Animal()

TypeError: Can't instantiate abstract class Animal without an implementation for abstract method 'make_sound'

In [186]:
class Employee:
    def __init__(self, name, salary):
        self.name = name          # public attribute
        self.__salary = salary    # private attribute

emp = Employee("Fedrick", 50000)
print(emp.name)
print(emp.__salary)

Fedrick

AttributeError: 'Employee' object has no attribute '__salary'

In [187]:
class Employee:
    def __init__(self, name):
        self.name = name   # public attribute

    def display_name(self):   # public method
        print(self.name)

emp = Employee("John")
emp.display_name()   # Accessible
print(emp.name)      # Accessible

John
John

In [188]:
class Employee:
    def __init__(self, name, age):
        self.name = name       # public
        self._age = age        # protected

class SubEmployee(Employee):
    def show_age(self):
        print("Age:", self._age)   # Accessible in subclass

emp = SubEmployee("Ross", 30)
print(emp.name)        # Public accessible
emp.show_age()         # Protected accessed through subclass

Ross
Age: 30

In [189]:
class Employee:
    def __init__(self, name, salary):
        self.name = name          # public
        self.__salary = salary    # private

    def show_salary(self):
        print("Salary:", self.__salary)

emp = Employee("Robert", 60000)
print(emp.name)          # Public accessible
emp.show_salary()        # Accessing private correctly
# print(emp.__salary)    # Error: Not accessible directly

Robert
Salary: 60000

In [190]:
class BankAccount:
    def __init__(self):
        self.balance = 1000

    def _show_balance(self):
        print(f"Balance: ₹{self.balance}")  # Protected method

    def __update_balance(self, amount):
        self.balance += amount             # Private method

    def deposit(self, amount):
        if amount > 0:
            self.__update_balance(amount)  # Accessing private method internally
            self._show_balance()           # Accessing protected method
        else:
            print("Invalid deposit amount!")

account = BankAccount()
account._show_balance()      # Works, but should be treated as internal
# account.__update_balance(500)  # Error: private method
account.deposit(500)         # Uses both methods internally

Balance: ₹1000
Balance: ₹1500

In [191]:
class Employee:
    def __init__(self):
        self.__salary = 50000  # Private attribute

    def get_salary(self):    # Getter method
        return self.__salary

    def set_salary(self, amount):   # Setter method
        if amount > 0:
            self.__salary = amount
        else:
            print("Invalid salary amount!")

emp = Employee()
print(emp.get_salary())  # Access salary using getter

emp.set_salary(60000)   # Update salary using setter
print(emp.get_salary())

50000
60000

In [192]:
s = "GFG"
it = iter(s)

print(next(it))
print(next(it))
print(next(it))

G
F
G

In [193]:
class EvenNumbers:
    def __iter__(self):
        self.n = 2  # Start from the first even number
        return self

    def __next__(self):
        x = self.n
        self.n += 2  # Increment by 2 to get the next even number
        return x

# Create an instance of EvenNumbers
even = EvenNumbers()
it = iter(even)

# Print the first five even numbers
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))

2
4
6
8
10

In [194]:
li = [100, 200, 300]
it = iter(li)

# Iterate until StopIteration is raised
while True:
    try:
        print(next(it))
    except StopIteration:
        print("End of iteration")
        break

100
200
300
End of iteration

In [195]:
# Iterable: list
numbers = [1, 2, 3]

# Iterator: created using iter()
it = iter(numbers)
print(next(it))
print(next(it))
print(next(it))

1
2
3

# Error Handling

In [196]:
n = 10
try:
    res = n / 0
except ZeroDivisionError:
    print("Can't be divided by zero!")

Can't be divided by zero!

In [197]:
try:
    n = 0
    res = 100 / n

except ZeroDivisionError:
    print("You can't divide by zero!")

except ValueError:
    print("Enter a valid number!")

else:
    print("Result is", res)

finally:
    print("Execution complete.")

You can't divide by zero!
Execution complete.

In [198]:
try:
    x = int("str")  # This will cause ValueError
    inv = 1 / x   # Inverse calculation

except ValueError:
    print("Not Valid!")

except ZeroDivisionError:
    print("Zero has no inverse!")

Not Valid!

In [199]:
a = ["10", "twenty", 30]  # Mixed list of integers and strings
try:
    total = int(a[0]) + int(a[1])  # 'twenty' cannot be converted to int

except (ValueError, TypeError) as e:
    print("Error", e)

except IndexError:
    print("Index out of range.")

Error invalid literal for int() with base 10: 'twenty'

In [200]:
def set(age):
    if age < 0:
        raise ValueError("Age cannot be negative.")
    print(f"Age set to {age}")

try:
    set(-5)
except ValueError as e:
    print(e)

Age cannot be negative.

In [201]:
class AgeError(Exception):
    pass

def set(age):
    if age < 0:
        raise AgeError("Age cannot be negative.")
    print(f"Age set to {age}")

try:
    set(-5)
except AgeError as e:
    print(e)

Age cannot be negative.

In [202]:
# Step 1: Define a custom exception class
class InvalidAgeError(Exception):
    def __init__(self, age, msg="Age must be between 0 and 120"):
        self.age = age
        self.msg = msg
        super().__init__(self.msg)

    def __str__(self):
        return f'{self.age} -> {self.msg}'

# Step 2: Use the custom exception in your code
def set_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError(age)
    else:
        print(f"Age set to: {age}")

# Step 3: Handling the custom exception
try:
    set_age(150)  # This will raise the custom exception
except InvalidAgeError as e:
    print(e)

150 -> Age must be between 0 and 120

In [203]:
class InvalidEmailError(Exception):
    def __init__(self, email, msg="Invalid email format"):
        self.email = email
        self.msg = msg
        super().__init__(self.msg)

    def __str__(self):
        return f"{self.email} -> {self.msg}"

def set_email(email):
    if "@" not in email:
        raise InvalidEmailError(email)
    print(f"Email set to: {email}")

try:
    set_email("userexample.com")
except InvalidEmailError as e:
    print(e)

userexample.com -> Invalid email format

# FIle handling

In [204]:
# Open the file in read mode
file = open("geeks.txt", "r")

# Read the entire content of the file
content = file.read()
print(content)

# Close the file
file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'geeks.txt'

## Numpy

In [205]:
import numpy as np

a = [9,3,3,5]
print(np.array(a))  # Converting list into numpy array

[9 3 3 5]

In [206]:
import numpy as np

n = np.array([9,3,3,5])
print(n.mean())    # Calculating mean

5.0

In [207]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

res = np.dot(A, A)    # Matrix multiplication
print(res)

[[ 7 10]
 [15 22]]

In [208]:
import numpy as np

a = np.random.normal(0, 1, 5)    # 5 values from normal distribution
print("Data:", a)
print("Mean:", np.mean(a))

Data: [-0.50934184 -0.1579079   1.13384432 -0.85336709  1.94856956]
Mean: 0.3123594087624263

# Pandas

In [209]:
import pandas as pd

df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

In [210]:
import pandas as pd

lst = ['Geeks', 'For', 'Geeks', 'is',
            'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [211]:
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [212]:
import pandas as pd

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict)

print(df)

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [213]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
        'Age': [25, 30, 22, 35, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df.index)  # Accessing the index

RangeIndex(start=0, stop=5, step=1)

In [217]:
df

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [214]:
# Set 'Name' column as the index
df_with_index = df.set_index('Name')
print(df_with_index)

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [215]:
# Reset the index back to the default integer index
df_reset = df.reset_index()
print(df_reset)

   index     Name  Age  Gender  Salary
0      0     John   25    Male   50000
1      1    Alice   30  Female   55000
2      2      Bob   22    Male   40000
3      3      Eve   35  Female   70000
4      4  Charlie   28    Male   48000

In [216]:
row = df.loc['Alice']
print(row)

KeyError: 'Alice'

In [218]:
# Set 'Age' as the new index
df_with_new_index = df.set_index('Age')
print(df_with_new_index)

        Name  Gender  Salary
Age
25      John    Male   50000
30     Alice  Female   55000
22       Bob    Male   40000
35       Eve  Female   70000
28   Charlie    Male   48000

In [219]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [220]:
value = df.iloc[2, 3]
print("Specific Cell Value:", value)

Specific Cell Value: 8428000

In [221]:
df1 = df.iloc[:, 0:2]

print(df1)

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [222]:
data = df[df['Age'] > 35].iloc[:, :]
print("\nFiltered Data based on Age > 35:\n", data)

Filtered Data based on Age > 35:
             Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
4        C.Gayle   40     100  4528000
6     K.Peterson   42      85  2528000

In [223]:
value = df.iloc[2, 3]
print("Specific Cell Value:", value)

Specific Cell Value: 8428000

In [224]:
df.set_index('Name', inplace=True)

custom = df.loc['A.B.D Villers':'S.Smith']
print(custom)

               Age  Weight   Salary
Name
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000

In [225]:
value = df.loc['V.Kohli', 'Salary']
print("\nValue of the Specific Cell (V.Kohli, Salary):", value)

Value of the Specific Cell (V.Kohli, Salary): 8428000

In [227]:
# import module
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],

                          'Age': [30, 35, 37, 33, 34, 30],

                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],

                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# display dataframe
dataFrame

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [228]:
# display dataframe
dataFrame

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [229]:
# filter dataframe
filtered_values = np.where((dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')))
print(filtered_values)
dataFrame.loc[filtered_values]

(array([0]),)

        Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

In [230]:
# filter dataframe
dataFrame.query('Salary  <= 100000 & Age < 40 & JOB.str.startswith("C").values')

        Name  Age  Salary   JOB
1   MONICA     35   93000  CHEF

In [231]:
dataFrame[(dataFrame['Salary']>=100000) & (dataFrame['Age']<40) & dataFrame['JOB'].str.startswith('P')][['Name','Age','Salary']]

         Name  Age  Salary
3    ROSS       33  120000

In [232]:
dataFrame[dataFrame.eval("Salary <=100000 & (Age <40) & JOB.str.startswith('A').values")]

        Name  Age  Salary     JOB
5   JOEY       30   95000  ARTIST

In [233]:
# importing pandas
import pandas as pd

# creating dataframe
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

In [234]:
pivot = df.pivot_table(index=['Product'],
                       values=['Amount'],
                       aggfunc='sum')
print(pivot)

          Amount
Product
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

In [235]:
# creating pivot table of total
# sales category-wise aggfunc = 'sum'
pivot = df.pivot_table(index=['Category'],
                       values=['Amount'],
                       aggfunc='sum')
print(pivot)

           Amount
Category
Fruit        1701
Vegetable    1197

In [236]:
pivot = df.pivot_table(index=['Product', 'Category'],
                       values=['Amount'], aggfunc='sum')
print(pivot)

                    Amount
Product  Category
Banana   Fruit        1091
Beans    Vegetable     626
Broccoli Vegetable     301
Carrots  Vegetable     270
Orange   Fruit         610

In [237]:
# 'mean', 'min'} will get median, mean and
# minimum of sales respectively
pivot = df.pivot_table(index=['Category'], values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
print(pivot)

           Amount
             mean median min
Category
Fruit      425.25  497.0  90
Vegetable  299.25  254.5  62

In [238]:
pivot = df.pivot_table(index=['Product'], values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
print(pivot)

              Amount
                mean median  min
Product
Banana    363.666667  384.0   90
Beans     626.000000  626.0  626
Broccoli  150.500000  150.5   62
Carrots   270.000000  270.0  270
Orange    610.000000  610.0  610

In [239]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age')
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [240]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],'Age': [25, 30, 35, 40],'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age',ascending=False)
print(sorted_df)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [241]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by=['Age', 'Score'])
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [242]:
import pandas as pd
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)

sorted_df = df_nan.sort_values(by="Age", na_position="first")
print(sorted_df)

      Name   Age
2  Charlie   NaN
1      Bob  22.0
3    David  22.0
0    Alice  28.0

In [243]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

df_sorted_by_index = df.sort_index()
print(df_sorted_by_index)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [244]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
df_sorted_by_index_desc = df.sort_index(ascending=False)
print(df_sorted_by_index_desc)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [245]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age', kind='quicksort')
print(sorted_df)

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
0    Alice   28     85
4      Eve   28     88

In [246]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age', kind='heapsort')
print(sorted_df)

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
4      Eve   28     88
0    Alice   28     85

In [247]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Name', key=lambda col: col.str.lower())
print(sorted_df)

      Name  Age  Score
0    Alice   28     85
1      Bob   22     90
2  Charlie   25     95
3    David   22     80
4      Eve   28     88

In [248]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [249]:
frames = [df, df1]

res1 = pd.concat(frames)
res1

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [250]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

In [251]:
res2 = pd.concat([df, df1], axis=1, join='inner')

res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,58,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,76,Anuj,32,Kannuaj,Phd,2000

In [252]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd'],
        'Mobile No': [97, 91, 58, 76]}

data2 = {'Name':['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
        'Age':[22, 32, 12, 52],
        'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons'],
        'Salary':[1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])


print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

In [253]:
res = pd.concat([df, df1], ignore_index=True)

res

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
4  Gaurav   22  Allahabad           MCA        NaN  1000.0
5    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [254]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
        'Age':[17, 14, 12, 52],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [255]:
frames = [df, df1 ]

res = pd.concat(frames, keys=['x', 'y'])
res

       Name  Age    Address Qualification
x 0     Jai   27     Nagpur           Msc
  1  Princi   24     Kanpur            MA
  2  Gaurav   22  Allahabad           MCA
  3    Anuj   32    Kannuaj           Phd
y 4    Abhi   17     Nagpur         Btech
  5  Ayushi   14     Kanpur           B.A
  6  Dhiraj   12  Allahabad          Bcom
  7  Hitesh   52    Kannuaj        B.hons

In [256]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')

print(df, "\n\n", s1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [257]:
res = pd.concat([df, s1], axis=1)

res

     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

In [258]:
import pandas as pd

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons

In [259]:
res = pd.merge(df, df1, on='key')

res

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [260]:
import pandas as pd

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

In [261]:
res1 = pd.merge(df, df1, on=['key', 'key1'])

res1

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [262]:
import pandas as pd

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

In [263]:
res = pd.merge(df, df1, how='left', on=['key', 'key1'])

res

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN

In [264]:
res1 = pd.merge(df, df1, how='right', on=['key', 'key1'])

res1

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K2   K0  Gaurav  22.0  Allahabad          Bcom
3  K3   K0     NaN   NaN    Kannuaj        B.hons

In [265]:
res2 = pd.merge(df, df1, how='outer', on=['key', 'key1'])

res2

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K1   K1  Princi  24.0        NaN           NaN
3  K2   K0  Gaurav  22.0  Allahabad          Bcom
4  K3   K0     NaN   NaN    Kannuaj        B.hons
5  K3   K1    Anuj  32.0        NaN           NaN

In [266]:
res3 = pd.merge(df, df1, how='inner', on=['key', 'key1'])

res3

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [267]:
import pandas as pd


data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1,index=['K0', 'K1', 'K2', 'K3'])

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

      Name  Age
K0     Jai   27
K1  Princi   24
K2  Gaurav   22
K3    Anuj   32

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [268]:
res = df.join(df1)

res

      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K1  Princi   24        NaN           NaN
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

In [269]:
res1 = df.join(df1, how='outer')

res1

      Name   Age    Address Qualification
K0     Jai  27.0  Allahabad           MCA
K1  Princi  24.0        NaN           NaN
K2  Gaurav  22.0    Kannuaj           Phd
K3    Anuj  32.0  Allahabad          Bcom
K4     NaN   NaN    Kannuaj        B.hons

In [270]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [271]:
res2 = df.join(df1, on='Key')

res2

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

In [272]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav'],
        'Age':[27, 24, 22]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kanpur'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=pd.Index(['K0', 'K1', 'K2'], name='key'))

index = pd.MultiIndex.from_tuples([('K0', 'Y0'), ('K1', 'Y1'),
                                   ('K2', 'Y2'), ('K2', 'Y3')],
                                   names=['key', 'Y'])

df1 = pd.DataFrame(data2, index= index)


print(df, "\n\n", df1)

       Name  Age
key
K0      Jai   27
K1   Princi   24
K2   Gaurav   22

           Address Qualification
key Y
K0  Y0  Allahabad           MCA
K1  Y1    Kannuaj           Phd
K2  Y2  Allahabad          Bcom
    Y3     Kanpur        B.hons

In [273]:
result = df.join(df1, how='inner')

result

          Name  Age    Address Qualification
key Y
K0  Y0     Jai   27  Allahabad           MCA
K1  Y1  Princi   24    Kannuaj           Phd
K2  Y2  Gaurav   22  Allahabad          Bcom
    Y3  Gaurav   22     Kanpur        B.hons